# use FONFLAGS = klq normally, use FONFLAG = klqm for NewGen safe version

FONFLAGS = klq
# FONFLAGS = klqm

# COMPFLAGS = v
COMPFLAGS =

# CONVFLAGS = vk
CONVFLAGS = k

HINTS = c:\bsr
AFMS = c:\afm\tex
VERSION = 1.00A

# following a little hokey ?
all: cm*.pfb

# .hex.out:
# 	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $<;

# .pfb.pfa:
#	c:\prog\pfatopfb -$(COMPFLAGS) $<;
# 	del $<;

cmb10.pfb: cmb10.hex cmb10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmb10.hex: cmb10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmbsy10.pfb: cmbsy10.hex cmbsy10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmbsy10.hex: cmbsy10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmbx10.pfb: cmbx10.hex cmbx10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmbx10.hex: cmbx10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmbx12.pfb: cmbx12.hex cmbx12.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmbx12.hex: cmbx12.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmbx5.pfb: cmbx5.hex cmbx5.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmbx5.hex: cmbx5.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmbx6.pfb: cmbx6.hex cmbx6.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmbx6.hex: cmbx6.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmbx7.pfb: cmbx7.hex cmbx7.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmbx7.hex: cmbx7.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmbx8.pfb: cmbx8.hex cmbx8.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmbx8.hex: cmbx8.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmbx9.pfb: cmbx9.hex cmbx9.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmbx9.hex: cmbx9.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmbxsl10.pfb: cmbxsl10.hex cmbxsl10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmbxsl10.hex: cmbxsl10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmbxti10.pfb: cmbxti10.hex cmbxti10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmbxti10.hex: cmbxti10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmcsc10.pfb: cmcsc10.hex cmcsc10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmcsc10.hex: cmcsc10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmcsc9.pfb: cmcsc9.hex cmcsc9.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmcsc9.hex: cmcsc9.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmdunh10.pfb: cmdunh10.hex cmdunh10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmdunh10.hex: cmdunh10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmex10.pfb: cmex10.hex cmex10.hnt
	c:\prog\fontone -$(FONFLAGS)bd -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmex10.hex: cmex10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmff10.pfb: cmff10.hex cmff10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmff10.hex: cmff10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmfi10.pfb: cmfi10.hex cmfi10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmfi10.hex: cmfi10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmfib8.pfb: cmfib8.hex cmfib8.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmfib8.hex: cmfib8.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cminch.pfb: cminch.hex cminch.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cminch.hex: cminch.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmitt10.pfb: cmitt10.hex cmitt10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmitt10.hex: cmitt10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmmi10.pfb: cmmi10.hex cmmi10.hnt
	c:\prog\fontone -$(FONFLAGS)b -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmmi10.hex: cmmi10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmmi12.pfb: cmmi12.hex cmmi12.hnt
	c:\prog\fontone -$(FONFLAGS)b -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmmi12.hex: cmmi12.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmmi5.pfb: cmmi5.hex cmmi5.hnt
	c:\prog\fontone -$(FONFLAGS)b -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmmi5.hex: cmmi5.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmmi6.pfb: cmmi6.hex cmmi6.hnt
	c:\prog\fontone -$(FONFLAGS)b -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmmi6.hex: cmmi6.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmmi7.pfb: cmmi7.hex cmmi7.hnt
	c:\prog\fontone -$(FONFLAGS)b -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmmi7.hex: cmmi7.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmmi8.pfb: cmmi8.hex cmmi8.hnt
	c:\prog\fontone -$(FONFLAGS)b -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmmi8.hex: cmmi8.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmmi9.pfb: cmmi9.hex cmmi9.hnt
	c:\prog\fontone -$(FONFLAGS)b -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmmi9.hex: cmmi9.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmmib10.pfb: cmmib10.hex cmmib10.hnt
	c:\prog\fontone -$(FONFLAGS)b -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmmib10.hex: cmmib10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmr10.pfb: cmr10.hex cmr10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmr10.hex: cmr10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmr12.pfb: cmr12.hex cmr12.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmr12.hex: cmr12.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmr17.pfb: cmr17.hex cmr17.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmr17.hex: cmr17.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmr5.pfb: cmr5.hex cmr5.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmr5.hex: cmr5.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmr6.pfb: cmr6.hex cmr6.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmr6.hex: cmr6.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmr7.pfb: cmr7.hex cmr7.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmr7.hex: cmr7.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmr8.pfb: cmr8.hex cmr8.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmr8.hex: cmr8.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmr9.pfb: cmr9.hex cmr9.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmr9.hex: cmr9.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmsl10.pfb: cmsl10.hex cmsl10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmsl10.hex: cmsl10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmsl12.pfb: cmsl12.hex cmsl12.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmsl12.hex: cmsl12.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmsl8.pfb: cmsl8.hex cmsl8.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmsl8.hex: cmsl8.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmsl9.pfb: cmsl9.hex cmsl9.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmsl9.hex: cmsl9.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmsltt10.pfb: cmsltt10.hex cmsltt10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmsltt10.hex: cmsltt10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmss10.pfb: cmss10.hex cmss10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmss10.hex: cmss10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmss12.pfb: cmss12.hex cmss12.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmss12.hex: cmss12.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmss17.pfb: cmss17.hex cmss17.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmss17.hex: cmss17.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmss8.pfb: cmss8.hex cmss8.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmss8.hex: cmss8.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmss9.pfb: cmss9.hex cmss9.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmss9.hex: cmss9.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmssbx10.pfb: cmssbx10.hex cmssbx10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmssbx10.hex: cmssbx10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmssdc10.pfb: cmssdc10.hex cmssdc10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmssdc10.hex: cmssdc10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmssi10.pfb: cmssi10.hex cmssi10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmssi10.hex: cmssi10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmssi12.pfb: cmssi12.hex cmssi12.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmssi12.hex: cmssi12.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmssi17.pfb: cmssi17.hex cmssi17.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmssi17.hex: cmssi17.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmssi8.pfb: cmssi8.hex cmssi8.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmssi8.hex: cmssi8.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmssi9.pfb: cmssi9.hex cmssi9.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmssi9.hex: cmssi9.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmssq8.pfb: cmssq8.hex cmssq8.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmssq8.hex: cmssq8.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmssqi8.pfb: cmssqi8.hex cmssqi8.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmssqi8.hex: cmssqi8.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmsy10.pfb: cmsy10.hex cmsy10.hnt
	c:\prog\fontone -$(FONFLAGS)b -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmsy10.hex: cmsy10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmsy5.pfb: cmsy5.hex cmsy5.hnt
	c:\prog\fontone -$(FONFLAGS)b -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmsy5.hex: cmsy5.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmsy6.pfb: cmsy6.hex cmsy6.hnt
	c:\prog\fontone -$(FONFLAGS)b -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmsy6.hex: cmsy6.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmsy7.pfb: cmsy7.hex cmsy7.hnt
	c:\prog\fontone -$(FONFLAGS)b -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmsy7.hex: cmsy7.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmsy8.pfb: cmsy8.hex cmsy8.hnt
	c:\prog\fontone -$(FONFLAGS)b -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmsy8.hex: cmsy8.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmsy9.pfb: cmsy9.hex cmsy9.hnt
	c:\prog\fontone -$(FONFLAGS)b -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmsy9.hex: cmsy9.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmtcsc10.pfb: cmtcsc10.hex cmtcsc10.hnt
	c:\prog\fontone -$(FONFLAGS)b -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmtcsc10.hex: cmtcsc10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmtex10.pfb: cmtex10.hex cmtex10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmtex10.hex: cmtex10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmtex8.pfb: cmtex8.hex cmtex8.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmtex8.hex: cmtex8.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmtex9.pfb: cmtex9.hex cmtex9.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmtex9.hex: cmtex9.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmti10.pfb: cmti10.hex cmti10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmti10.hex: cmti10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmti12.pfb: cmti12.hex cmti12.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmti12.hex: cmti12.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmti7.pfb: cmti7.hex cmti7.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmti7.hex: cmti7.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmti8.pfb: cmti8.hex cmti8.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmti8.hex: cmti8.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmti9.pfb: cmti9.hex cmti9.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmti9.hex: cmti9.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmtt10.pfb: cmtt10.hex cmtt10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmtt10.hex: cmtt10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmtt12.pfb: cmtt12.hex cmtt12.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmtt12.hex: cmtt12.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmtt8.pfb: cmtt8.hex cmtt8.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmtt8.hex: cmtt8.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmtt9.pfb: cmtt9.hex cmtt9.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmtt9.hex: cmtt9.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmu10.pfb: cmu10.hex cmu10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmu10.hex: cmu10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

cmvtt10.pfb: cmvtt10.hex cmvtt10.hnt
	c:\prog\fontone -$(FONFLAGS) -w $(AFMS) -h $(HINTS) $*.hex
	c:\prog\pfatopfb $*.pfa
	del $*.pfa

cmvtt10.hex: cmvtt10.out
	c:\prog\convert -$(CONVFLAGS) -x $(VERSION) $*.out;

