@echo off
call mkextra cmb10
call mkextra cmbx10
call mkextra cmbx12
call mkextra cmbx5
call mkextra cmbx6
call mkextra cmbx7
call mkextra cmbx8
call mkextra cmbx9
call mkextra cmbxsl10
call mkextra cmbxti10
call mkextra cmcsc10
call mkextra cmdunh10
call mkextra cmff10
call mkextra cmfi10
call mkextra cmfib8
call mkextra cmitt10
call mkextra cmr10
call mkextra cmr12
call mkextra cmr17
call mkextra cmr5
call mkextra cmr6
call mkextra cmr7
call mkextra cmr8
call mkextra cmr9
call mkextra cmsl10
call mkextra cmsl12
call mkextra cmsl8
call mkextra cmsl9
call mkextra cmsltt10
call mkextra cmss10
call mkextra cmss12
call mkextra cmss17
call mkextra cmss8
call mkextra cmss9
call mkextra cmssbx10
call mkextra cmssdc10
call mkextra cmssi10
call mkextra cmssi12
call mkextra cmssi17
call mkextra cmssi8
call mkextra cmssi9
call mkextra cmssq8
call mkextra cmssqi8
call mkextra cmtcsc10
call mkextra cmti10
call mkextra cmti12
call mkextra cmti7
call mkextra cmti8
call mkextra cmti9
call mkextra cmtt10
call mkextra cmtt12
call mkextra cmtt8
call mkextra cmtt9
call mkextra cmu10
call mkextra cmvtt10
