cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/absolute.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/access.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/atou.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/cnf.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/concat.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/concat3.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/concatn.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/db.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/debug.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/dir.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/elt-dirs.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/expand.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/extend-fname.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/file-p.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/find-suffix.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/fn.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/fontmap.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/getopt.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/getopt1.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/hash.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/kdefault.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/knj.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/kpathsea.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/kpsestat.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/kpsewhich.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/line.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/magstep.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/make-suffix.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/path-elt.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/pathsearch.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/proginit.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/progname.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/putenv.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/readable.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/readlink.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/rm-suffix.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/str-list.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/str-llist.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/tex-file.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/tex-glyph.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/tex-hush.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/tex-make.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/tilde.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/uppercasify.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/variable.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/version.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/win32lib.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/xbasename.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/xcalloc.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/xdirname.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/xdirtest.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/xfopen.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/xfseek.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/xfseeko.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/xftell.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/xftello.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/xgetcwd.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/xmalloc.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/xopendir.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/xputenv.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/xrealloc.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/xstat.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/xstrdup.c
cl -nologo -c -I. -DWIN32=1 -DMAKE_KPSE_DLL=1 kpathsea/dirent.c
